# https://github.com/cross-rs/cross/wiki/Recipes#openssl
[target.armv7-unknown-linux-musleabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update && apt-get install --assume-yes libssl-dev:armhf"
]
