version: 3

tasks:
  build-setup:
    cmds:
      - socat TCP-LISTEN:5555,fork TCP:localhost:22
      - podman --remote system connection add cloudlab-oracle-arm --identity ~/.ssh/id_ed25519 ssh://root@cloudlab-oracle-arm:5555/run/podman/podman.sock
      - podman --remote system connection default cloudlab-oracle-arm
      - podman --log-level=debug --remote info --debug
      - podman --remote info

  docker-build-generate:
    cmds:
      - podman build . -f Dockerfile.generate -t blesswinsamuel/ebpf-firewall:generate

  docker-build:
    cmds:
      - podman build . -t blesswinsamuel/ebpf-firewall

  go-generate:
    cmds:
      - podman create blesswinsamuel/ebpf-firewall:generate > /tmp/container_id
      - defer: rm /tmp/container_id
      - defer: podman rm -f $(cat /tmp/container_id)
      - podman cp $(cat /tmp/container_id):/generated/ ./
      - defer: rm -rf ./generated
      - cp -r generated/* ./internal/firewall/
    deps:
      - docker-build-generate

  go-build:
    cmds:
      - GOOS=linux GOARCH=arm64 go build -o ebpf-firewall ./cmd/ebpf-firewall

  copy-to-router:
    cmds:
      - ssh root@router "pkill -f ebpf-firewall" || true
      - scp ebpf-firewall root@router:/root/ebpf-firewall
      - ssh root@router "nix-shell -p autoPatchelfHook --run 'autoPatchelf /root/ebpf-firewall'"

  nix-build:
    cmds:
      # - nix run github:nix-community/gomod2nix#gomod2nix -- generate
      # - nix build --eval-store auto -j0 --store 'ssh-ng://root@cloudlab-oracle-arm' --builders "ssh-ng://root@cloudlab-oracle-arm aarch64-linux" '.#packages.aarch64-linux.default'
      - nix build --eval-store auto -j0 --store 'ssh-ng://root@cloudlab-oracle-arm' '.#packages.aarch64-linux.default'
      # - nix build --eval-store auto -j0 --store 'ssh-ng://root@raspberry-pi-4' '.#packages.aarch64-linux.default'

  nix-copy-to-router:
    cmds:
      - nix copy --verbose --no-check-sigs --from 'ssh-ng://root@cloudlab-oracle-arm' --to 'ssh-ng://root@raspberry-pi-4' '.#packages.aarch64-linux.default'
