version: 3

tasks:
  build-setup:
    cmds:
      - socat TCP-LISTEN:5555,fork TCP:localhost:22
      - podman --remote system connection add cloudlab-oracle-arm --identity ~/.ssh/id_ed25519 ssh://root@cloudlab-oracle-arm:5555/run/podman/podman.sock
      - podman --remote system connection default cloudlab-oracle-arm
      - podman --log-level=debug --remote info --debug
      - podman --remote info

  docker-build:
    cmds:
      - podman build . -t blesswinsamuel/router-monitor

  go-build:
    cmds:
      - podman build . -t blesswinsamuel/router-monitor
      - podman create blesswinsamuel/router-monitor > /tmp/container_id
      - defer: rm /tmp/container_id
      - defer: podman rm -f $(cat /tmp/container_id)
      - mkdir -p bin
      - podman cp $(cat /tmp/container_id):/src/target/debug/router-monitor ./bin/router-monitor

  copy-to-router:
    cmds:
      - scp bin/router-monitor root@router:/root/router-monitor
      - ssh root@router "nix-shell -p autoPatchelfHook --run 'autoPatchelf /root/router-monitor'"
