{
 "title": "Lanpilot",
 "description": "Dashboard for monitoring router traffic and internet connection status",
 "tags": [ "lanpilot" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "localips",
    "label": "Local IPs",
    "query": "label_values(lanpilot_packets_total, dst)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(lanpilot_internet_connection_is_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is a generated dashboard. Any changes made here will be lost on the next generation."
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "x": 0, "y": 3, "h": 1, "w": 24 } },
  {
   "title": "Internet",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(lanpilot_internet_connection_is_up{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Internet Downtime",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(max(lanpilot_internet_connection_is_up{instance=~\"$instance\"})[$__range])) * $__range_s"
    }
   ]
  },
  {
   "title": "Average Connection Latency",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(lanpilot_internet_connection_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(lanpilot_internet_connection_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Max Connection Latency",
   "type": "stat",
   "gridPos": { "x": 12, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(lanpilot_internet_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "No. of devices",
   "type": "stat",
   "description": "Number of devices connected",
   "gridPos": { "x": 16, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(last_over_time((lanpilot_arp_devices{instance=~\"$instance\"} == 2)[$__range]))"
    }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "bargauge",
   "gridPos": { "x": 20, "y": 4, "w": 4, "h": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(src) (increase(lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum by(dst) (increase(lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Connection Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(lanpilot_internet_connection_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval]) / rate(lanpilot_internet_connection_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ addr }} average"
    },
    {
     "expr": "1 - max(lanpilot_internet_connection_is_up{instance=~\"$instance\"})",
     "legendFormat": "down"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(lanpilot_internet_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "95p"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(lanpilot_internet_connection_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "50p"
    }
   ]
  },
  {
   "title": "Connection down",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "1 - lanpilot_internet_connection_is_up{instance=~\"$instance\"}",
     "legendFormat": "{{ addr }} down"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "table",
   "gridPos": { "x": 0, "y": 13, "w": 24, "h": 12 },
   "targets": [
    {
     "expr": "sum by (ip_addr, hw_addr, hostname, device) (lanpilot_arp_devices{instance=~\"$instance\"})"
    },
    {
     "expr": "label_move(sum by (dst) (increase(lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__range]) > 0), \"dst\", \"ip_addr\")"
    },
    {
     "expr": "label_move(sum by (dst) (increase(lanpilot_packets_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__range]) > 0), \"dst\", \"ip_addr\")"
    },
    {
     "expr": "label_move(sum by (src) (increase(lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__range]) > 0), \"src\", \"ip_addr\")"
    },
    {
     "expr": "label_move(sum by (src) (increase(lanpilot_packets_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__range]) > 0), \"src\", \"ip_addr\")"
    }
   ]
  },
  { "title": "Network Traffic", "type": "row", "gridPos": { "x": 0, "y": 25, "h": 1, "w": 24 } },
  {
   "title": "Total Bytes Downloaded - by local IP (pie chart)",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 26, "w": 12, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(dst) (\n    increase(\n      lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__range]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"dst\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) (keep_last_value(\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Total Bytes Uploaded - by local IP (pie chart)",
   "type": "piechart",
   "gridPos": { "x": 12, "y": 26, "w": 12, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(src) (\n    increase(\n      lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__range]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"src\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) (keep_last_value(\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Total bytes downloaded - by local IP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 38, "w": 6, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(dst) (\n    increase(\n      lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"dst\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) ((\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Total bytes uploaded - by local IP",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 38, "w": 6, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(src) (\n    increase(\n      lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"src\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) ((\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Download Data Rate - by local IP",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 38, "w": 6, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(dst) (\n    rate(\n      lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__rate_interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"dst\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) ((\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Upload Data Rate - by local IP",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 38, "w": 6, "h": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(src) (\n    rate(\n      lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__rate_interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"src\", \"(.*)\"\n)\n* on(ip_addr) group_left(hw_addr, device, hostname) ((\n    sum by (ip_addr, hw_addr, device, hostname) (lanpilot_arp_devices{instance=~\"$instance\"})\n  ) * 0 + 1)\n",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Total bytes downloaded",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 50, "w": 6, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(src) (\n    increase(\n      lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"src\", \"(.*)\"\n)",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Total bytes uploaded",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 50, "w": 6, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(dst) (\n    increase(\n      lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"dst\", \"(.*)\"\n)",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Download Data Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 50, "w": 6, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(src) (\n    rate(\n      lanpilot_bytes_total{dst=~\"$localips\",src=~\"internet\",instance=~\"$instance\"}[$__rate_interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"src\", \"(.*)\"\n)",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  },
  {
   "title": "Upload Data Rate",
   "type": "timeseries",
   "gridPos": { "x": 18, "y": 50, "w": 6, "h": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "\nlabel_replace(\n  sum by(dst) (\n    rate(\n      lanpilot_bytes_total{src=~\"$localips\",dst=~\"internet\",instance=~\"$instance\"}[$__rate_interval]\n    ) > 0\n  ),\n  \"ip_addr\", \"$1\", \"dst\", \"(.*)\"\n)",
     "legendFormat": "{{ hostname }} ({{ ip_addr }})"
    }
   ]
  }
 ]
}