name: Create Release

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.0" # The Go version to download (if necessary) and use.

      - name: Build go application
        run: |
          docker build -t blesswinsamuel/router-monitor:latest .
          docker run --rm --entrypoint cat blesswinsamuel/router-monitor:latest /router-monitor > router-monitor
          chmod +x router-monitor
          tar czf router-monitor-linux-arm.tar.gz router-monitor

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./router-monitor-linux-arm.tar.gz
          asset_name: router-monitor-linux-arm.tar.gz
          asset_content_type: application/x-tar

      - uses: blesswinsamuel/github-actions/notify@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
