name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: blesswinsamuel/github-actions/docker-build-and-push@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          docker-build-platforms: linux/arm64
