name: Docker

on:
  push:
    branches:
      - main

    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: aarch64-unknown-linux-gnu
          args: "--locked --release"
          strip: true
      - uses: blesswinsamuel/github-actions/docker-build-and-push@main
        with:
          docker-registry: docker.io
          docker-image-name: ${{ github.repository }}
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          telegram-bot-token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram-chat-id: ${{ secrets.TELEGRAM_CHAT_ID }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          docker-build-platforms: linux/arm64
